serviceId: CUSTOMERSERVICE

spring:
  datasource:
    url: jdbc:mysql://mysqlprod:3307/document_locker?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        general_statistics: true
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 1000